GET http://localhost:3000/api/v1/longest-duration-movies

###
POST http://localhost:3000/api/v1/new-movie
Content-Type: application/json

{
  "tconst": "adam_richard",
  "primaryTitle": "richard_567",
  "runtimeMinutes": 122,
  "genres": "male"
}

###
GET http://localhost:3000/api/v1/top-rated-movies

###
GET http://localhost:3000/api/v1/genre-movies-with-subtotals

###
POST http://localhost:3000/api/v1/update-runtime-minutes